import { createElement } from 'react';
import {
  LuArrowLeft,
  LuArrowRight,
  LuArrowUp,
  LuBell,
  LuBookmark,
  LuCamera,
  LuCheck,
  LuChevronDown,
  LuChevronUp,
  LuCircle,
  LuCircleAlert,
  LuCircleCheck,
  LuCompass,
  LuEllipsis,
  LuEye,
  LuEyeOff,
  LuHash,
  LuHeart,
  LuHistory,
  LuHouse,
  LuImage,
  LuInbox,
  LuLogOut,
  LuMessageCircle,
  LuPause,
  LuPenLine,
  LuPlay,
  LuPlus,
  LuReply,
  LuSearch,
  LuSend,
  LuShare2,
  LuTrash2,
  LuUser,
  LuUserPlus,
  LuUsers,
  LuVideo,
  LuVolume2,
  LuVolumeX,
  LuX,
  LuZap,
} from 'react-icons/lu';

const makeFilledIcon = (BaseIcon) => function FilledIcon(props) {
  return createElement(BaseIcon, {
    ...props,
    fill: 'currentColor',
    strokeWidth: 2.2,
  });
};

export const icons = {
  arrowLeft: LuArrowLeft,
  arrowRight: LuArrowRight,
  arrowUp: LuArrowUp,
  share: LuShare2,
  notification: LuBell,
  notificationActive: makeFilledIcon(LuBell),
  bookmark: makeFilledIcon(LuBookmark),
  bookmarkOutline: LuBookmark,
  comment: LuMessageCircle,
  commentSolid: makeFilledIcon(LuMessageCircle),
  message: LuMessageCircle,
  messageActive: makeFilledIcon(LuMessageCircle),
  explore: LuCompass,
  exploreActive: makeFilledIcon(LuCompass),
  compass: LuCompass,
  more: LuEllipsis,
  like: makeFilledIcon(LuHeart),
  likeOutline: LuHeart,
  home: LuHouse,
  homeActive: makeFilledIcon(LuHouse),
  image: LuImage,
  inbox: LuInbox,
  search: LuSearch,
  history: LuHistory,
  send: LuSend,
  pen: LuPenLine,
  plus: LuPlus,
  checkCircle: LuCircleCheck,
  check: LuCheck,
  reply: LuReply,
  logout: LuLogOut,
  star: LuZap,
  trash: LuTrash2,
  user: LuUser,
  userActive: makeFilledIcon(LuUser),
  userAdd: LuUserPlus,
  users: LuUsers,
  video: LuVideo,
  camera: LuCamera,
  close: LuX,
  warning: LuCircleAlert,
  chevronDown: LuChevronDown,
  chevronUp: LuChevronUp,
  play: LuPlay,
  pause: LuPause,
  volumeHigh: LuVolume2,
  volumeXmark: LuVolumeX,
  bolt: LuZap,
  hashtag: LuHash,
  circle: LuCircle,
  eye: LuEye,
  eyeOff: LuEyeOff,
};

export const actionIcons = {
  home: icons.home,
  homeActive: icons.homeActive,
  explore: icons.explore,
  exploreActive: icons.exploreActive,
  notifications: icons.notification,
  notificationsActive: icons.notificationActive,
  messages: icons.message,
  messagesActive: icons.messageActive,
  create: icons.plus,
  saved: icons.bookmarkOutline,
  savedActive: icons.bookmark,
  search: icons.search,
  profile: icons.user,
  profileActive: icons.userActive,
  logout: icons.logout,
  like: icons.like,
  likeOutline: icons.likeOutline,
  comment: icons.comment,
  commentSolid: icons.commentSolid,
  reply: icons.reply,
  save: icons.bookmark,
  follow: icons.userAdd,
  share: icons.share,
  send: icons.send,
  close: icons.close,
};
